# Generated by Django 4.2 on 2025-08-19 03:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='百岳名稱')),
                ('elevation', models.IntegerField(verbose_name='海拔高度 (公尺)')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='經緯度座標')),
                ('difficulty', models.CharField(choices=[('beginner', '初級'), ('intermediate', '中級'), ('advanced', '高級'), ('expert', '專家級')], max_length=20, verbose_name='難度等級')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='來回距離 (公里)')),
                ('duration_days', models.IntegerField(default=1, verbose_name='預估天數')),
                ('status', models.CharField(choices=[('incomplete', '未完成'), ('completed', '已完成'), ('planned', '計劃中')], default='incomplete', max_length=20, verbose_name='完成狀態')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='計劃日期')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('route_info', models.TextField(blank=True, verbose_name='路線資訊')),
                ('notes', models.TextField(blank=True, verbose_name='個人筆記')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '台灣百岳',
                'verbose_name_plural': '台灣百岳',
                'ordering': ['-elevation'],
            },
        ),
    ]
